name: stateful_props

version: 0.1.2+8
description: Encapsulate behavior easily across Widgets. Improve readability by reducing nesting and promoting code locality.
author: shawn@gskinner.com
homepage: https://github.com/gskinnerTeam/flutter-stateful-props

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
